# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temu.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'temu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntemu.proto\"\xa3\x01\n\x07\x61ppInfo\x12\x0f\n\x07titanid\x18\x01 \x01(\x0c\x12\n\n\x02ua\x18\x03 \x01(\x0c\x12\n\n\x02os\x18\x04 \x01(\r\x12\x0b\n\x03uid\x18\x05 \x01(\t\x12\x11\n\trepackage\x18\x0b \x01(\r\x12\x13\n\x0b\x61\x63\x63\x65sstoken\x18\x0c \x01(\t\x12\x15\n\rcustomPayload\x18\r \x01(\x0c\x12\x10\n\x08\x61uthType\x18\x11 \x01(\r\x12\x11\n\tsceneType\x18\x13 \x01(\r\"q\n\x13TitanSessionRequest\x12\x18\n\x10\x65ncryptedAppInfo\x18\x07 \x01(\x0c\x12\x13\n\x0brequestType\x18\n \x01(\r\x12\x17\n\x0fprotocolVersion\x18\x0b \x01(\r\x12\x12\n\nisPushConn\x18\x0c \x01(\x08\"H\n\x15MulticastGroupKeyInfo\x12\r\n\x05\x61ppId\x18\x01 \x01(\r\x12\x0f\n\x07\x62izType\x18\x02 \x01(\r\x12\x0f\n\x07groupId\x18\x03 \x01(\t\"\xfa\x01\n\rTitanUpstream\x12\r\n\x05\x61ppId\x18\x01 \x01(\r\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x10\n\x08protocol\x18\x03 \x01(\r\x12\x10\n\x08\x63ompress\x18\x04 \x01(\r\x12\x0c\n\x04host\x18\x06 \x01(\t\x12\x0f\n\x07\x61ppinfo\x18\x07 \x01(\x0c\x12\x1c\n\x14sessionResumptionReq\x18\x08 \x01(\x0c\x12\x0c\n\x04\x62ody\x18\t \x01(\x0c\x12\x13\n\x0bupstreamSeq\x18\x0b \x01(\x04\x12\r\n\x05\x63onId\x18\x0c \x01(\x04\x12\r\n\x05\x63txId\x18\r \x01(\x04\x12\'\n\x07keyInfo\x18\x0e \x01(\x0b\x32\x16.MulticastGroupKeyInfo\"\xd5\x01\n\x0fTitanDownstream\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x10\n\x08protocol\x18\x02 \x01(\r\x12\x11\n\terrorCode\x18\x03 \x01(\r\x12\x0f\n\x07\x62izCode\x18\x04 \x01(\r\x12\x13\n\x0b\x62izErrorMsg\x18\x05 \x01(\t\x12\x10\n\x08\x63ompress\x18\x06 \x01(\r\x12\x11\n\textension\x18\t \x01(\x0c\x12\x0c\n\x04\x62ody\x18\n \x01(\x0c\x12\x15\n\rdownstreamSeq\x18\x0b \x01(\x04\x12\r\n\x05\x63onId\x18\x0c \x01(\x04\x12\r\n\x05\x63txId\x18\r \x01(\x04\"W\n\x04Sync\x12\x14\n\x0cuidOffsetMap\x18\x01 \x01(\x04\x12\x18\n\x10titanidOffsetMap\x18\x02 \x01(\x04\x12\x0f\n\x07syncAll\x18\x03 \x01(\x08\x12\x0e\n\x06\x61\x63\x63\x65pt\x18\x04 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPINFO']._serialized_start=15
  _globals['_APPINFO']._serialized_end=178
  _globals['_TITANSESSIONREQUEST']._serialized_start=180
  _globals['_TITANSESSIONREQUEST']._serialized_end=293
  _globals['_MULTICASTGROUPKEYINFO']._serialized_start=295
  _globals['_MULTICASTGROUPKEYINFO']._serialized_end=367
  _globals['_TITANUPSTREAM']._serialized_start=370
  _globals['_TITANUPSTREAM']._serialized_end=620
  _globals['_TITANDOWNSTREAM']._serialized_start=623
  _globals['_TITANDOWNSTREAM']._serialized_end=836
  _globals['_SYNC']._serialized_start=838
  _globals['_SYNC']._serialized_end=925
# @@protoc_insertion_point(module_scope)
